//
//  House.swift
//  CatanProbGenerator
//
//  Created by FredLohner on 5/Dec/15.
//  Copyright (c) 2015 FredLohner. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

class CatanHouse: UIView {
    override func drawRect(rect: CGRect) {
        House.drawCanvas1()
    }
}


public class House: NSObject {

    //// Drawing Methods

    public class func drawCanvas1() {

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRectMake(0, 8, 20, 10))
        UIColor.blueColor().setFill()
        rectanglePath.fill()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(0, 8))
        bezierPath.addLineToPoint(CGPointMake(20, 8))
        bezierPath.addLineToPoint(CGPointMake(10.53, 1))
        bezierPath.addLineToPoint(CGPointMake(0, 8))
        bezierPath.closePath()
        UIColor.blueColor().setFill()
        bezierPath.fill()
    }

}
